version: '3.8'

services:
  backend:
    build:
      context: .  # Root directory
      dockerfile: Dockerfile  # Now at root
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend  # Ensure live reload
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - rag-network

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge
